apiVersion: apps/v1
kind: Deployment
metadata:
  name: begonia
spec:
  replicas: 1
  selector:
    matchLabels:
      name: begonia
  template:
    metadata:
      labels:
        name: begonia
    spec:
      containers:
        - name: app
          imagePullPolicy: Always
          image: docker.io/faux/begonia-proxy:latest
          ports:
            - name: proxy
              containerPort: 3438
          env:
            - name: RUST_LOG
              value: info
          resources:
            limits:
              cpu: "1"
              memory: 1G
          readinessProbe:
            httpGet:
              path: "/healthcheck"
              port: 3438
          livenessProbe:
            httpGet:
              path: "/healthcheck"
              port: 3438
---
apiVersion: v1
kind: Service
metadata:
  name: begonia
spec:
  selector:
    name: begonia
  ports:
    - name: proxy
      port: 3438
