[package]
name = "begonia-proxy"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
env_logger = "0.11"
httparse = "1"
k8s-openapi = { version = "0.17.0", default-features = false, features = ["v1_22"] }
kube = { version = "0.79", features = ["client"] }
lazy_static = "1"
log = "0.4"
regex = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
trust-dns-resolver = "0.22"
url = "2"

[profile.release]
lto = true
